// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace ElemagicGameplayTags
{
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Light);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Heavy);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Jump);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Projectile);

	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attacking);

	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash);

	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dashing);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_DashedInAir);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Invulnerable);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Dash);

	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);

	// Event.Attack.* Tags
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_EnableHitbox);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_DisableHitbox);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_ResetHitTargets);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_EndAttack);

	// State.* Tags (受击反馈)
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Hurt);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Knockback);

	// Combo.* Tags
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combo_WindowOpen);

	// Element.* Tags（7 种元素）
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Fire);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Water);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Earth);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Wind);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Lightning);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Light);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Dark);

	// Input.* Tags（技能栏 1-4 + 合成按键）
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Skill1);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Skill2);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Skill3);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Skill4);
	ELEMAGIC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Synthesize);
}
